# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('ci', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nacimiento', models.DateField()),
                ('enfermedad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vistas.Usuario')),
                ('especialidad', models.CharField(max_length=80)),
                ('pacientes', models.ManyToManyField(blank=True, to='vistas.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vistas.Usuario')),
                ('area', models.CharField(max_length=80)),
                ('alumnos', models.ManyToManyField(blank=True, to='vistas.Paciente')),
            ],
        ),
    ]
