# Generated by Django 2.0.6 on 2018-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0003_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cita',
            name='medico',
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ManyToManyField(to='vistas.Medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='representante',
            field=models.ManyToManyField(to='vistas.Representante'),
        ),
    ]
