# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0005_auto_20180708_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='representante',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
